export const colors = {
    primary: "#F9EBC8",
    primaryDarker: "#DAE5D0",
    primaryLighter: "#FEFBE7",
    secondary: "#A0BCC2",
    confirmButton:"#B8F1B0",
    disabledButton:"#C5C5C5",
    disabledFont:"#A5A5A5",
    confirmPanel:"#A0BCC2",
    confirmPanelBorder:"#A5D89E",
    backDialog: "#D1D1D1",
    buttonDialog: "#7882A4",
    textInputBack: "#DBDFFD",
    textInputColor: "#242F9B",
    error : "#ff0000",
    authScreensBack: "#9BA3EB",
    activityIndicator: "#242F9B",
    border:"#E0D3B4",
}